// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Werner_DMV_API.Models
{
    public partial class DMV_APIContext : DbContext
    {
        public DMV_APIContext()
        {
        }

        public DMV_APIContext(DbContextOptions<DMV_APIContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DMV> DMV { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<InfractionInfo> InfractionInfo { get; set; }
        public virtual DbSet<Infractions> Infractions { get; set; }
        public virtual DbSet<LawEnforcement> LawEnforcement { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DMV>(entity =>
            {
                entity.Property(e => e.DMVID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DMVPassword)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DMVUserName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasMany(d => d.License)
                    .WithMany(p => p.DMV)
                    .UsingEntity<Dictionary<string, object>>(
                        "LicenseIssuer",
                        l => l.HasOne<Licenses>().WithMany().HasForeignKey("LicenseID").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__LicenseIs__Licen__4222D4EF"),
                        r => r.HasOne<DMV>().WithMany().HasForeignKey("DMVID").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__LicenseIs__DMVID__412EB0B6"),
                        j =>
                        {
                            j.HasKey("DMVID", "LicenseID").HasName("PK__LicenseI__03AEDF504A4BCEF9");

                            j.ToTable("LicenseIssuer");

                            j.IndexerProperty<string>("DMVID").HasMaxLength(20).IsUnicode(false);

                            j.IndexerProperty<string>("LicenseID").HasMaxLength(20).IsUnicode(false);
                        });
            });

            modelBuilder.Entity<Drivers>(entity =>
            {
                entity.HasKey(e => e.DriverID)
                    .HasName("PK__Drivers__F1B1CD24F2ACE6AF");

                entity.Property(e => e.DriverID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DAddress)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DCity)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DFirstName)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DLastName)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DSSN)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DState)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DZip)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<InfractionInfo>(entity =>
            {
                entity.HasKey(e => e.IInfoID)
                    .HasName("PK__Infracti__3E783365B2BD9175");

                entity.Property(e => e.IInfoID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.IType)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Infractions>(entity =>
            {
                entity.HasKey(e => e.InfractionID)
                    .HasName("PK__Infracti__66F5B69752255F6D");

                entity.Property(e => e.InfractionID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.IInfoID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LawEnID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LicenseID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.HasOne(d => d.IInfo)
                    .WithMany(p => p.Infractions)
                    .HasForeignKey(d => d.IInfoID)
                    .HasConstraintName("FK__Infractio__IInfo__48CFD27E");

                entity.HasOne(d => d.LawEn)
                    .WithMany(p => p.Infractions)
                    .HasForeignKey(d => d.LawEnID)
                    .HasConstraintName("FK__Infractio__LawEn__4AB81AF0");

                entity.HasOne(d => d.License)
                    .WithMany(p => p.Infractions)
                    .HasForeignKey(d => d.LicenseID)
                    .HasConstraintName("FK__Infractio__Licen__49C3F6B7");
            });

            modelBuilder.Entity<LawEnforcement>(entity =>
            {
                entity.HasKey(e => e.LawEnID)
                    .HasName("PK__LawEnfor__1FCFC0664E20C6D4");

                entity.Property(e => e.LawEnID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LEPassword)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LEUserName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Licenses>(entity =>
            {
                entity.HasKey(e => e.LicenseID)
                    .HasName("PK__Licenses__72D600A25EA5C44B");

                entity.Property(e => e.LicenseID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DriverID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.VehicleID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.HasOne(d => d.Driver)
                    .WithMany(p => p.Licenses)
                    .HasForeignKey(d => d.DriverID)
                    .HasConstraintName("FK__Licenses__Driver__3B75D760");

                entity.HasOne(d => d.Vehicle)
                    .WithMany(p => p.Licenses)
                    .HasForeignKey(d => d.VehicleID)
                    .HasConstraintName("FK__Licenses__Vehicl__3C69FB99");
            });

            modelBuilder.Entity<Vehicles>(entity =>
            {
                entity.HasKey(e => e.VehicleID)
                    .HasName("PK__Vehicles__476B54B22228DB88");

                entity.Property(e => e.VehicleID)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.VehicleType)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}