// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Werner_DMV_API.Models
{
    public partial class Drivers
    {
        public Drivers()
        {
            Licenses = new HashSet<Licenses>();
        }

        public string DriverID { get; set; }
        public string DFirstName { get; set; }
        public string DLastName { get; set; }
        public string DSSN { get; set; }
        public string DAddress { get; set; }
        public string DCity { get; set; }
        public string DState { get; set; }
        public string DZip { get; set; }

        public virtual ICollection<Licenses> Licenses { get; set; }
    }
}