// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Werner_DMV_API.Models
{
    public partial class InfractionInfo
    {
        public InfractionInfo()
        {
            Infractions = new HashSet<Infractions>();
        }

        public string IInfoID { get; set; }
        public string IType { get; set; }
        public decimal IFine { get; set; }

        public virtual ICollection<Infractions> Infractions { get; set; }
    }
}