// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Werner_DMV_API.Models
{
    public partial class LawEnforcement
    {
        public LawEnforcement()
        {
            Infractions = new HashSet<Infractions>();
        }

        public string LawEnID { get; set; }
        public string LEUserName { get; set; }
        public string LEPassword { get; set; }

        public virtual ICollection<Infractions> Infractions { get; set; }
    }
}