// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Werner_DMV_API.Models
{
    public partial class Licenses
    {
        public Licenses()
        {
            Infractions = new HashSet<Infractions>();
            DMV = new HashSet<DMV>();
        }

        public string LicenseID { get; set; }
        public string DriverID { get; set; }
        public string VehicleID { get; set; }

        public virtual Drivers Driver { get; set; }
        public virtual Vehicles Vehicle { get; set; }
        public virtual ICollection<Infractions> Infractions { get; set; }

        public virtual ICollection<DMV> DMV { get; set; }
    }
}