// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Werner_DMV_API.Models
{
    public partial class Vehicles
    {
        public Vehicles()
        {
            Licenses = new HashSet<Licenses>();
        }

        public string VehicleID { get; set; }
        public string VehicleType { get; set; }

        public virtual ICollection<Licenses> Licenses { get; set; }
    }
}